services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    # volumes:
    # - ./backend:/app
    # - ./backend/src/database/us-census.db:/app/backend/src/database/us-census.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
